name: Memory Leak Check

on:
  push:
    branches:
      - main

jobs:
  check-memory-leaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile the C program
      run: |
        sudo apt install valgrind -y
        gcc -o test main.c

    - name: Run Valgrind to check for memory leaks
      run: |
        valgrind_output=$(valgrind --leak-check=full --error-exitcode=1 ./my_program 2>&1)
        echo "$valgrind_output"

    - name: Fail if memory leaks are found
      if: ${{ failure() }}
      run: |
        echo "Memory leaks detected! Check the Valgrind output above."
        exit 1